---
- hosts: all
  tags: always
  become: true
  tasks:

    - name: Install Base
      pacman:
        name:
          - wget
          - git
          - curl
          - gnupg

    # Your tasks here

            #- import_tasks: gitsetup.yml

