- name: This is a sudo test
  hosts: localhost
  tasks:

    - name: Install vim
      pacman:
        name:
          - vim
        state: present
      become: true

    - name: Create a file as pablo
      file:
        path: /home/pablo/testfile
        state: touch

    - name: create folder test
      when: not folder_exists
  become: true
  vars:
    folder_exists: "'/path/to/folder' in lookup('fileglob', '/path/to/folder')"
