---

  - name: Playbook with vault
    hosts: localhost
    tasks:
      - name: Include Vault
        ansible.builtin.include_vars:
          file: pass.yml

      - name: Print pass variable
        ansible.builtin.debug:
          var: mypassword
